import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://influencemodels.agency';
  const lastModified = new Date('2026-06-22');

  const routes: { route: string; priority: number; changeFrequency: 'weekly' | 'monthly' | 'yearly' }[] = [
    { route: '', priority: 1.0, changeFrequency: 'weekly' },
    { route: '/marketplace', priority: 0.95, changeFrequency: 'weekly' },
    { route: '/influencer/des-001', priority: 0.95, changeFrequency: 'weekly' },
    { route: '/influencer/kaylese-062', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/services', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/services/content', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/business', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/shoots', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/commercials', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/events', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/bottle-girls', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/pricing', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/pricing-guide', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/model-booking', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/about', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/contact', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/faq', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/join', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/terms', priority: 0.3, changeFrequency: 'yearly' },
    { route: '/blog', priority: 0.8, changeFrequency: 'weekly' },
    { route: '/blog/why-influencer-marketing-is-dominating-2025', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/roi-of-influencer-marketing-vs-traditional-ads', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/how-miami-brands-are-winning-with-local-influencers', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/ugc-vs-branded-content-what-converts-better', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/music-video-models-the-secret-weapon-for-viral-videos', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/how-to-go-viral-on-tiktok-with-music', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/viral-challenge-marketing-guide', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/best-ways-to-promote-your-song-on-instagram', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/hire-influencer-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/music-video-models', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/ugc-creators-florida', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/instagram-models-for-hire', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/event-models-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/book-models-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/models-for-photoshoot', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-agency-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/viral-challenge-creators', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/music-reaction-videos', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/bottle-girls-miami', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/song-promotion-instagram', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/actress-models-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/casting-agency-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/voiceover-talent-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/shop', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/influencer/shay-050', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/kat-051', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nikki-052', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ayana-053', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/maria-002', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/genesis-003', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ferrari-004', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/lexi-044', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/peach-045', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/yenny-018', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/gabriella-019', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nadia-020', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/simone-021', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/sydnie-022', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/bianca-055', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/breyanna-056', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/bree-041', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/breanna-046', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/seahra-026', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/kady-010', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/leila-009', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nya-042', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/malibu-040', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashley-mar-044', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashley-morris-043', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/mika-057', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/gracejenn-058', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/yuli-059', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashleypena-060', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/hannah-061', priority: 0.7, changeFrequency: 'monthly' },
  ];

  return routes.map(({ route, priority, changeFrequency }) => ({
    url: `${baseUrl}${route}`,
    lastModified,
    changeFrequency,
    priority,
  }));
}
