import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://influencecreators.marketing';
  const lastModified = new Date('2026-06-28');

  const routes: { route: string; priority: number; changeFrequency: 'weekly' | 'monthly' | 'yearly' }[] = [
    { route: '', priority: 1.0, changeFrequency: 'weekly' },
    { route: '/marketplace', priority: 0.95, changeFrequency: 'weekly' },
    { route: '/influencer/des-001', priority: 0.95, changeFrequency: 'weekly' },
    { route: '/influencer/kaylese-062', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/services', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/services/content', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/business', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/shoots', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/commercials', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/services/events', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/start', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/about', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/contact', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/faq', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/join', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/terms', priority: 0.3, changeFrequency: 'yearly' },
    { route: '/blog', priority: 0.8, changeFrequency: 'weekly' },
    { route: '/blog/why-influencer-marketing-is-dominating-2025', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/roi-of-influencer-marketing-vs-traditional-ads', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/how-miami-brands-are-winning-with-local-influencers', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/ugc-vs-branded-content-what-converts-better', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/music-video-creators-the-secret-weapon-for-viral-videos', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/how-to-go-viral-on-tiktok-with-music', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/viral-challenge-marketing-guide', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/best-ways-to-promote-your-song-on-instagram', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/blog/miami-influencer-marketing-guide-2026', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/hire-influencer-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/how-to-promote-song-on-tiktok', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/hire-influencers-for-restaurant', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/best-creator-marketplaces-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/ugc-vs-traditional-ads', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-miami', priority: 0.9, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-fort-lauderdale', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-boca-raton', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-palm-beach', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-west-palm-beach', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-delray-beach', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-hollywood', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/ugc-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/music-video-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-wynwood', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-south-beach', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-brickell', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-coral-gables', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/music-video-creators', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-miami-es', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/events/miami-influencer-summit-2026', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/ugc-creators-florida', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/instagram-creators-for-hire', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/event-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/book-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/creators-for-photoshoot', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/influencer-marketing-miami-main', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/viral-challenge-creators', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/music-reaction-videos', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/bottle-girls-miami', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/song-promotion-instagram', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/actress-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/casting-network-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/voiceover-creators-miami', priority: 0.85, changeFrequency: 'monthly' },
    { route: '/shop', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/influencer/shay-050', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/kat-051', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nikki-052', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ayana-053', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/maria-002', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/genesis-003', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ferrari-004', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/lexci-044', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/peach-045', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/yenny-018', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/gabriella-019', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nadia-020', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/simone-021', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/sydnie-022', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/bianca-055', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/breyanna-056', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/bree-041', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/breanna-046', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/seahra-026', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/kady-010', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/leila-009', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/nya-042', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/malibu-040', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashley-mar-044', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashley-morris-043', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/mika-057', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/gracejenn-058', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/yuli-059', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/ashleypena-060', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/hannah-061', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/influencer/madeline-063', priority: 0.7, changeFrequency: 'monthly' },

    // Previously missing — core pages
    { route: '/quote', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/start', priority: 0.7, changeFrequency: 'monthly' },
    { route: '/music-video-booking', priority: 0.8, changeFrequency: 'monthly' },
    { route: '/creators-for-shoots', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/ugc-content', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/event-creators', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/for-fashion-brands', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/influencer-campaigns', priority: 0.75, changeFrequency: 'monthly' },
    { route: '/label-campaigns', priority: 0.75, changeFrequency: 'monthly' },

    // Previously missing — /lp landing pages
    { route: '/lp/advertise-my-event', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/best-way-to-promote-an-event', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/bottle-girls-boca-raton', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/bottle-girls-delray-beach', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/bottle-girls-palm-beach', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/event-advertising', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/event-promotion-company', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/hire-bottle-girls-boynton-beach', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/hire-influencers-for-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/hire-local-influencers', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/hire-tiktok-influencers', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/hostess-network', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/influencer-marketplace-miami', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/influencer-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/influencer-marketing-miami-main', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/influencer-marketing-network', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/influencers-in-miami', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/music-for-instagram-reels', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/music-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/music-marketing-companies', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/music-video-promotion', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/paid-influencer-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/palm-beach-event-promotion', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/promote-my-event', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/promote-my-music', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/promote-your-music', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/promoter-girls-palm-beach', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-content-creator', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-influencer-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-marketplace-for-influencers', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-content-creation', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-content-creator', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-content-creator-for-small-business', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-influencer-marketplace', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-influencer-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-influencer-marketing-agency', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-creator-network', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/social-media-video-creator', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/tiktok-influencers-for-hire', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/ugc-ads', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/ugc-content-creation', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/ugc-marketing', priority: 0.6, changeFrequency: 'monthly' },
    { route: '/lp/ugc-videos', priority: 0.6, changeFrequency: 'monthly' },
  ];

  return routes.map(({ route, priority, changeFrequency }) => ({
    url: `${baseUrl}${route}`,
    lastModified,
    changeFrequency,
    priority,
  }));
}
